### ISSUE TITLE
Error encountered trying to when use with iTerm2 3.2.0 on Mac

### ISSUE THREAD

**Issue by interactiveRob** [LazoCoder/Pokemon-Terminal#157]
Here's the error I get trying to run 'pokemon pikachu' after installing pokemon-terminal with pip3

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/pokemon", line 11, in <module>
    load_entry_point('pokemon-terminal==1.2.0', 'console_scripts', 'pokemon')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pokemonterminal/main.py", line 113, in main
    scripter.change_terminal(target.get_path())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pokemonterminal/scripter.py", line 81, in change_terminal
    TERMINAL_PROVIDER.change_terminal(image_file_path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pokemonterminal/terminal/adapters/iterm.py", line 26, in change_terminal
    stdin = ItermProvider.__osa_script_fmt.format(path)
AttributeError: type object 'ItermProvider' has no attribute '_ItermProvider__osa_script_fmt'
```

**Comment by sylveon** [comment]
Fixed in a commit, reinstalling should fix it.

**Comment by interactiveRob** [comment]
@sylveon Thanks so much for the quick fix. Gotta catch em' all!

**Comment by jimmyorourke** [comment]
Oof, that was caused by a bad merge commit. I don't really understand how though..
